all:
  children:
    vms:
      children:
        vms_test:
          hosts:
            itsidevfsd0036.xaas.epfl.ch:
              k0s_role_worker: true
              k0s_role_controller: true
            itsidevfsd0037.xaas.epfl.ch:
              k0s_role_worker: true
              k0s_role_controller: true
          vars:
            inventory_environment: test
            ansible_user: root
            ansible_python_interpreter: /usr/bin/python3.9
