__mongodb_keybase: /keybase/team/epfl_mongodb/
__mongodb_db_inventory_file: "{{ 'mongodb_db_inventory-' + inventory_environment + '.yml' }}"
mongodb_db_inventory: "{{ lookup('file', __mongodb_keybase + __mongodb_db_inventory_file) | from_yaml }}"

__mongodb_s3_file: "{{ 'aws-cli-credentials-' + inventory_environment + '.yml' }}"
mongodb_s3: "{{ lookup('file', __mongodb_keybase + __mongodb_s3_file) | from_yaml }}"
mongodb_s3_dir: "{{ 'mongodb_' + inventory_environment + '_bkp' }}"
mongodb_s3_bucket_path: "{{ 's3:https://s3.epfl.ch/' + mongodb_s3.bucket_name + '/' +mongodb_s3_dir }}"

mongosh_version: 2.2.6
mongodb_major_version: 7
__mongodb_minor_version: 0
__mongodb_patch_version: 11
mongodb_version: "{{ mongodb_major_version }}.{{ __mongodb_minor_version }}.{{ __mongodb_patch_version}}"
mongodb_port: 27017
mongodb_storage_path: /srv/mongo/data
mongodb_backup_path: /srv/mongo/backup
mongodb_restore_path: /srv/mongo/restore
