- include_tasks:
    file: vm-access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access

- include_tasks:
    file: vm-os.yml
    apply:
      tags:
        - vm
        - vm.os
        - vm.os.upgrade
  tags:
    - vm
    - vm.os
    - vm.os.upgrade

- include_tasks:
    file: vm-lvm.yml
    apply:
      tags:
        - vm
        - vm.lvm
  tags:
    - vm
    - vm.lvm

- include_tasks:
    file: mongo-install.yml
    apply:
      tags:
        - vm
        - mongo
        - mongo.install
  tags:
    - vm
    - mongo
    - mongo.install

- include_tasks:
    file: mongo-setup.yml
    apply:
      tags:
        - vm
        - mongo
        - mongo.setup
  tags:
    - vm
    - mongo
    - mongo.setup

- include_tasks:
    file: mongo-manage.yml
    apply:
      tags:
        - vm
        - mongo
        - mongo.manage
  tags:
    - vm
    - mongo
    - mongo.manage

- include_tasks:
    file: tools.yml
    apply:
      tags:
        - never
  tags:
    - tools.connect
    - debug
