- include_tasks:
    file: vm-access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access

- include_tasks:
    file: vm-os.yml
    apply:
      tags:
        - vm
        - vm.os
        - vm.os.upgrade
  tags:
    - vm
    - vm.os
    - vm.os.upgrade

- include_tasks:
    file: vm-lvm.yml
    apply:
      tags:
        - vm
        - vm.lvm
  tags:
    - vm
    - vm.lvm

- include_tasks:
    file: vm-vip-check.yml
    apply:
      tags:
        - never
        - mongo.backup
        - vm.vip
  tags:
    - mongo.backup
    - vm.vip

- include_tasks:
    file: vm-vip.yml
    apply:
      tags:
        - never
        - vm
        - vm.vip
  tags:
    - vm
    - vm.vip

- include_tasks:
    file: mongo-install.yml
    apply:
      tags:
        - vm
        - mongo
        - mongo.install
  tags:
    - vm
    - mongo
    - mongo.install

- include_tasks:
    file: mongo-setup.yml
    apply:
      tags:
        - vm
        - mongo
        - mongo.setup
  tags:
    - vm
    - mongo
    - mongo.setup

- include_tasks:
    file: mongo-manage.yml
    apply:
      tags:
        - vm
        - mongo
        - mongo.manage
  tags:
    - vm
    - mongo
    - mongo.manage

- include_tasks:
    file: mongo-backup.yml
    apply:
      tags:
        - never
        - mongo.backup
  tags:
    - mongo.backup

- include_tasks:
    file: tools.yml
    apply:
      tags:
        - never
  tags:
    - tools.connect
    - tools.restic
    - debug
