- include_tasks:
    file: vm-access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access

- include_tasks:
    file: vm-os.yml
    apply:
      tags:
        - vm
        - vm.os
        - vm.os.upgrade
  tags:
    - vm
    - vm.os
    - vm.os.upgrade

- include_tasks:
    file: vm-lvm.yml
    apply:
      tags:
        - vm
        - vm.lvm
  tags:
    - vm
    - vm.lvm

- include_tasks:
    file: vm-vip-check.yml
    apply:
      tags:
        - never
        - mongo.backup
        - mongo.cron
        - mongo.restore
        - vm.vip
  tags:
    - mongo.backup
    - mongo.cron
    - mongo.restore
    - vm.vip

- include_tasks:
    file: vm-vip.yml
    apply:
      tags:
        - never
        - vm.vip
  tags:
    - vm.vip

- include_tasks:
    file: mongo-install.yml
    apply:
      tags:
        - mongo
        - mongo.install
  tags:
    - mongo
    - mongo.install

- include_tasks:
    file: mongo-setup.yml
    apply:
      tags:
        - mongo
        - mongo.setup
  tags:
    - mongo
    - mongo.setup

- include_tasks:
    file: mongo-manage.yml
    apply:
      tags:
        - mongo
        - mongo.manage
  tags:
    - mongo
    - mongo.manage

- include_tasks:
    file: mongo-restic-init-s3.yml
    apply:
      tags:
        - never
        - mongo.backup
        - mongo.restore
  tags:
    - mongo.backup
    - mongo.restore

- include_tasks:
    file: mongo-backup.yml
    apply:
      tags:
        - never
        - mongo.backup
  tags:
    - mongo.backup
    - mongo.cron
    - mongo.unlock

- include_tasks:
    file: mongo-restore.yml
    apply:
      tags:
        - never
        - mongo.restore
  tags:
    - mongo.restore

- include_tasks:
    file: ssl.yml
    apply:
      tags:
        - never
  tags:
    - ssl.private_key
    - ssl.install_certificate

- include_tasks:
    file: tools.yml
    apply:
      tags:
        - never
  tags:
    - tools.aws
    - tools.connect
    - tools.restic
    - tools.vip
    - debug
