- include_tasks:
    file: vm-access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access

- include_tasks:
    file: vm-os.yml
    apply:
      tags:
        - vm
        - vm.os
        - vm.os.upgrade
  tags:
    - vm
    - vm.os
    - vm.os.upgrade

    
