- tags: always
  include_vars: mongo-vars.yml

- name: Restic is initialized on s3
  shell:
    cmd: |
      set -e
      export RESTIC_PASSWORD="{{ mongodb_s3.restic_password }}"
      export AWS_ACCESS_KEY_ID="{{ mongodb_s3.aws_access_key_id }}"
      export AWS_SECRET_ACCESS_KEY="{{ mongodb_s3.aws_secret_access_key }}"
      set -x
      if restic -r {{ mongodb_s3_bucket_path }} snapshots; then
        echo "ALREADY_DONE"
        exit 0
      fi
      restic -r {{ mongodb_s3_bucket_path }} init
      
  register: _restic_init
  changed_when: >-
    "ALREADY_DONE" not in _restic_init.stdout
