- tags: always
  include_vars: mongo-vars.yml

- name: Lock database
  community.mongodb.mongodb_shell:
    login_user: "{{ mongodb_db_inventory.admin.user }}"
    login_password: "{{ mongodb_db_inventory.admin.password }}"
    eval: "db.fsyncLock()"
  when: "{{ vip_active }}"

- name: Backup database
  ansible.builtin.shell: mongodump --uri='mongodb://{{ mongodb_db_inventory.admin.user }}:{{ mongodb_db_inventory.admin.password }}@{{ inventory_hostname}}' --out {{ mongodb_backup_path }}
  when: "{{ vip_active }}"


# - name: Unlock database
#   community.mongodb.mongodb_shell:
#     login_user: "{{ mongodb_db_inventory.admin.user }}"
#     login_password: "{{ mongodb_db_inventory.admin.password }}"
#     eval: "db.fsyncUnlock()"
#   tags:
#     - mongo.backup
