- tags: always
  include_vars: mongo-vars.yml

- name: "`mongo` volume group"
  community.general.lvg:
    vg: mongo
    pvs: /dev/sdb
    pesize: 32

# https://docs.ansible.com/ansible/latest/collections/community/general/lvol_module.html
- name: Create a logical volume per databases
  community.general.lvol:
    vg: mongo
    lv: "{{ item.key }}"
    size: 2g
  loop: "{{ mongodb_db_inventory | dict2items }}"

- name: Format the XFS filesystem
  community.general.filesystem:
    fstype: xfs
    dev: "/dev/mongo/{{ item.key }}"
  loop: "{{ mongodb_db_inventory | dict2items }}"

- name: "Mount the lvs on {{ mongodb_storage_path }}"
  ansible.posix.mount:
    # Note: MongoDB uses decimall representation of ASCII value for special char
    #       For now, we only allow hyphens and undescores.
    path: "{{ mongodb_storage_path }}/{{ item.key | replace('-','.45') | replace('_','.95') }}"
    src: "/dev/mongo/{{ item.key }}"
    fstype: xfs
    state: mounted
  loop: "{{ mongodb_db_inventory | dict2items }}"

- name: "`mongod` is the owner and group of the storage path"
  ansible.builtin.file:
    path: "{{ mongodb_storage_path }}/{{ item.key | replace('-','.45') | replace('_','.95') }}"
    owner: mongod
    group: mongod
    mode: '0700'
  loop: "{{ mongodb_db_inventory | dict2items }}"
