
- name: upgrade all packages
  ansible.builtin.dnf: 
    name: '*'
    state: latest
  when: >- 
    "vm.os.upgrade" in ansible_run_tags

- name: Convenient packages
  ansible.builtin.dnf: 
    name: "{{ item }}"
    state: latest
  with_items:
    - nmap
    - telnet
    - tmux
    - pip
  
# Allow ansible to manage database
- name: Install PyMongo
  ansible.builtin.pip:
    name: pymongo
